sudo: required
dist: xenial
group: edge
language: python
services:
  - docker

# Disable depth (for ./autogen.sh --system to pass)
git:
  depth: 9999999

# Notes: we run the linters only on Fedora 28 to save time. This may miss some
# issues on CentOS but the chance is very low.
env:
  matrix:
    - DOCKER_IMAGE=ovirtorg/vdsm-test-centos
      MAKE_TARGET=tests-py27
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-28
      MAKE_TARGET=tests-py27
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-28
      MAKE_TARGET=tests-py36
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-28
      MAKE_TARGET=lint
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-29
      MAKE_TARGET=check

matrix:
  fast_finish: true
  allow_failures:
    # Fedora 29 uses python 3.7, breaking compatibility again by making "async"
    # a keyword.
    - env: DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-29 MAKE_TARGET=check

before_install:
  - docker --version
  - docker pull $DOCKER_IMAGE

# Note: network tests on centos fail on low coverage, so we use lower value.
script:
  - |
    docker run \
    --env TRAVIS_CI=1 \
    --env PYLINT_JOBS=1 \
    --env NETWORK_PY27_COVERAGE=38 \
    --privileged \
    --rm \
    -it \
    -v `pwd`:/vdsm:Z $DOCKER_IMAGE \
    bash -c "cd /vdsm && ./autogen.sh --system && make && make $MAKE_TARGET"
