sudo: required
dist: xenial
group: edge
language: python
services:
  - docker

# Disable depth (for ./autogen.sh --system to pass)
git:
  depth: 9999999

env:
  matrix:
    - DOCKER_IMAGE=ovirtorg/vdsm-test-centos
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-28
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-29
    - DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-rawhide

matrix:
  fast_finish: true
  allow_failures:
    - env: DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-29
    - env: DOCKER_IMAGE=ovirtorg/vdsm-test-fedora-rawhide

before_install:
  - docker --version
  - docker pull $DOCKER_IMAGE

# Note: network tests on centos fail on low coverage, so we use lower value.
script:
  - |
    docker run \
    --env TRAVIS_CI=1 \
    --env NETWORK_PY27_COVERAGE=38 \
    --privileged \
    --rm \
    -it \
    -v `pwd`:/vdsm:Z $DOCKER_IMAGE \
    bash -c "cd /vdsm && ./autogen.sh --system && make && make check"
