archs:
  - ppc64le:
      distributions:
        - el7
  - s390x:
      distributions:
        - fc28
  - x86_64:
      distributions:
        - el7
        - fc28

release_branches:
  master:
    - ovirt-master
  ovirt-4.3:
    - ovirt-4.3
  ovirt-4.2:
    - ovirt-4.2

stages:
  - build-artifacts:
      substages:
        - build-py27
        - build-py36:
            distributions:
              - fc28
  - check-patch:
      archs:
        - x86_64
      substages:
        - install:
            run-if:
              file-changed:
                - 'vdsm.spec.in'
                - '*Makefile.am'
                - 'automation/*'
                - 'build-aux/*'
        - linters:
            distributions:
              - fc28
        - tests-py27:
            runtime-requirements:
              host-distro: same
        - tests-py36:
            runtime-requirements:
              host-distro: same
            distributions:
              - fc28
  - check-network:
      archs:
        - x86_64
      substages:
        - functional-linux-bridge:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - el7
        - functional-ovs-switch:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - el7
